# Generated by Django 4.1.2 on 2022-11-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('contenido', models.CharField(max_length=100)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUno.contacto')),
            ],
        ),
    ]
