# Generated by Django 4.1.2 on 2022-11-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0002_apuntes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuntes',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
